"""
urdf_generator.py
=================

根据网页 /arm_config 发布的 JSON（与 ROBOT_UI/example.json 同结构），动态生成 URDF 文件。

支持的字段映射：
  joints[i].type          → 轴类型：axial=tangent_z, tangential=hinge（这里一律 revolute）
  joints[i].link.l        → DH a_{i-1}（沿 x 偏移长度）
  joints[i].link.d        → DH d_i（沿 z 偏移长度）
  joints[i].link.alpha    → DH α_{i-1}（绕 x 扭转角）
  joints[i].link.theta    → DH θ_i（绕 z 零位偏角，写到 joint origin rpy）
  joints[i].link.mass     → link 质量
  joints[i].link.center_of_mass → 质心 xyz
  joints[i].actuator_mass → 简化合到 link mass（不单独建模）

不回写（URDF 写死后动不了）：
  - 关节轴方向（axial=tangent z，tangential=hinge x，但保留 axial 的轴向=绕 z 旋转的语义）
  - 几何形状（用 cylinder/box 简化外观，不影响 mass）
"""
from __future__ import annotations

import json
import os
from typing import Dict


URDF_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!--
  two_axis_arm.urdf — AUTO-GENERATED by urdf_generator.py
  Source: /arm_config JSON (ROBOT_UI/example.json style)
  DOF: {dof}  arm_name: {arm_name}
-->
<robot name="{robot_name}">

  <material name="arm_white">
    <color rgba="0.95 0.95 0.95 1" />
  </material>
  <material name="arm_motor">
    <color rgba="0.05 0.05 0.05 1" />
  </material>
  <material name="tip_red">
    <color rgba="1.0 0.2 0.2 1" />
  </material>

  <!-- Base link (anchored to world; ManiSkill fix_root_link=True freezes it) -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="0.02"/></geometry>
      <material name="arm_motor"/>
    </visual>
  </link>
{links_xml}
{joints_xml}

  <!-- End-effector tip (fixed) -->
  <joint name="wrist_tip_joint" type="fixed">
    <parent link="link_{dof}"/>
    <child link="wrist_tip"/>
    <origin xyz="{tip_l} 0 0" rpy="0 0 0"/>
  </joint>
  <link name="wrist_tip">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="0.012"/></geometry>
      <material name="tip_red"/>
    </visual>
  </link>
</robot>
"""


def _format_vec(xyz):
    if isinstance(xyz, (list, tuple)) and len(xyz) >= 3:
        return f"{xyz[0]} {xyz[1]} {xyz[2]}"
    return "0 0 0"


def _rod_inertia(mass: float, length: float) -> tuple:
    """细杆绕质心的主惯性：I_xx = I_yy = m*l²/12, I_zz ≈ 0。"""
    if mass <= 0 or length <= 0:
        return (1e-6, 1e-6, 1e-6)
    i_perp = mass * length * length / 12.0
    return (i_perp, i_perp, 1e-4)


def generate_link_xml(idx: int, joint_def: Dict) -> str:
    """生成第 idx 个 link 的 XML。

    link 的几何外观由 this_def.link.{l,d,alpha,theta} 反映：
      - l:    沿 x 偏移（影响 box 长度 + visual origin x）
      - d:    沿 z 偏移（视觉几何的 z 偏）
      - alpha: 绕 x 扭转
      - theta: 绕 z 零位偏
    """
    link = joint_def.get("link", {})
    mass = float(link.get("mass", 0.1)) + float(joint_def.get("actuator_mass", 0.0))
    com = link.get("center_of_mass", [0, 0, 0])
    l    = float(link.get("l",     0.0))
    d    = float(link.get("d",     0.0))
    alpha = float(link.get("alpha", 0.0))
    theta = float(link.get("theta", 0.0))

    # 视觉几何：让外形明显呈现"机械感"
    #   link 是 axial（沿 z 偏距 d）→ cylinder 立在 z 上，高度 ∝ d，半径 0.04
    #   link 是 tangential（沿 x 伸出 l）→ box 沿 x 长度 = l，截面 0.04×0.04
    if abs(l) > 1e-4:
        size_geom = f'<box size="{max(0.05, abs(l))} 0.04 0.04"/>'
        vis_origin_xyz = f"{l/2} 0 {d}"
        vis_origin_rpy = f"{alpha} 0 {theta}"
    else:
        cyl_h = max(0.08, abs(d) * 2 + 0.08)
        size_geom = f'<cylinder radius="0.04" length="{cyl_h}"/>'
        vis_origin_xyz = f"0 0 {d + cyl_h/2 - 0.01}"
        vis_origin_rpy = "0 0 0"

    # 转动惯量（细杆近似），长度取 max(l, |d|, 0.02)
    L = max(abs(l), abs(d), 0.02)
    Ixx, Iyy, Izz = _rod_inertia(mass, L)

    return f'''  <link name="link_{idx}">
    <inertial>
      <origin xyz="{_format_vec(com)}" rpy="0 0 0"/>
      <mass value="{mass}"/>
      <inertia ixx="{Ixx}" ixy="0" ixz="0" iyy="{Iyy}" iyz="0" izz="{Izz}"/>
    </inertial>
    <visual>
      <origin xyz="{vis_origin_xyz}" rpy="{vis_origin_rpy}"/>
      <geometry>{size_geom}</geometry>
      <material name="arm_white"/>
    </visual>
    <collision>
      <origin xyz="{vis_origin_xyz}" rpy="{vis_origin_rpy}"/>
      <geometry>{size_geom}</geometry>
    </collision>
  </link>'''


def generate_joint_xml(idx: int, prev_def: Dict, this_def: Dict) -> str:
    """生成第 idx 个 joint 的 XML。

    简化的几何策略：
      - joint_<idx> 的 origin = (上一段的 l, 0, 上一段的 d)，把 link 沿父 link 的 x/z 偏出
      - joint_<idx> 的 rpy  = (上一段的 alpha, 0, 上一段的 theta)
      - joint_<idx> 的轴：
          joint_1 → z（axial：基座绕 z 旋转）
          否则    → x（tangential：水平面内俯仰）
      - 这一段 (this_def) 的 l/d/alpha/theta 全部用于 link visual origin（在 link XML 里）
    """
    prev_link = prev_def.get("link", {}) if isinstance(prev_def, dict) else {}

    l_prev   = float(prev_link.get("l",    0.0))
    d_prev   = float(prev_link.get("d",    0.0))
    alpha_p  = float(prev_link.get("alpha", 0.0))
    theta_p  = float(prev_link.get("theta", 0.0))

    axis = "0 0 1" if idx == 1 else "1 0 0"

    parent = "base_link" if idx == 1 else f"link_{idx-1}"
    return f'''  <joint name="joint_{idx}" type="revolute">
    <parent link="{parent}"/>
    <child  link="link_{idx}"/>
    <origin xyz="{l_prev} 0 {d_prev}" rpy="{alpha_p} 0 {theta_p}"/>
    <axis  xyz="{axis}"/>
    <limit lower="-3.14159" upper="3.14159" effort="100" velocity="3.0"/>
  </joint>'''


def generate_urdf(arm_config: dict, output_path: str) -> str:
    """
    arm_config: 与 example.json 同结构
        {
          "arm_name": "example",
          "dof": 2,
          "joints": {
            "joint1": {...}, "joint2": {...}, ...
          }
        }
    返回写入的文件路径。
    """
    dof = int(arm_config.get("dof", 2))
    if dof < 1 or dof > 7:
        raise ValueError(f"dof={dof} 超出支持范围 1..7")

    arm_name = arm_config.get("arm_name", "dynamic_arm")
    robot_name = f"{arm_name}_dof{dof}"

    joint_defs = arm_config.get("joints", {}) or {}
    keys = [k for k in sorted(joint_defs.keys()) if k.startswith("joint")] or [f"joint{i+1}" for i in range(dof)]

    # 取前 dof 个
    keys = keys[:dof]

    # 给每个 idx 准备 def；缺失则补默认值
    defaults = {
        "type": "tangential",
        "link": {"l": 0.1, "d": 0.0, "alpha": 0.0, "theta": 0.0,
                 "mass": 0.1, "center_of_mass": [0.05, 0, 0]},
        "actuator_mass": 0.03,
    }
    defs = []
    for i, k in enumerate(keys, start=1):
        d = joint_defs.get(k, {}) or {}
        # 缺字段补默认
        d = {
            "type": d.get("type", defaults["type"]),
            "link": {**defaults["link"], **(d.get("link") or {})},
            "actuator_mass": d.get("actuator_mass", defaults["actuator_mass"]),
        }
        d["link"]["center_of_mass"] = d["link"].get("center_of_mass") or [0.0, 0.0, 0.0]
        defs.append(d)

    # 补到 dof（不太可能触发，但保险）
    while len(defs) < dof:
        defs.append(defaults.copy())

    # 生成 link / joint XML
    # 注：joint i 的 origin = (l_{i-1}, d_{i-1}, alpha_{i-1}, theta_i)
    # 所以生成 joint_i 需要 defs[i-2] 和 defs[i-1]
    # 第一个关节 joint_1 通常 a=0, d=base 距 → 用 defs[0].link 的 l/d/alpha = 0（基座无偏）
    # 为统一：joint_1 的 origin 写成 (0, 0, d_of_defs[0], alpha=0)
    # 这里采用更通用的写法：
    base_def = {"link": {"l": 0.0, "d": 0.0, "alpha": 0.0}}  # 虚拟"前一帧"用 0
    links_xml = []
    joints_xml = []
    for idx in range(1, dof + 1):
        this_def = defs[idx - 1]
        prev_def = defs[idx - 2] if idx >= 2 else base_def
        links_xml.append(generate_link_xml(idx, this_def))
        joints_xml.append(generate_joint_xml(idx, prev_def, this_def))

    # tip 偏移用最后一个 link 的 l（放到 tip 外延相同方向）
    tip_l = float(defs[-1]["link"].get("l", 0.05))

    urdf = URDF_TEMPLATE.format(
        dof=dof,
        arm_name=arm_name,
        robot_name=robot_name,
        links_xml="\n".join(links_xml),
        joints_xml="\n".join(joints_xml),
        tip_l=tip_l,
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(urdf)

    return output_path


if __name__ == "__main__":
    # 自检：用 example.json 跑一次
    example_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "example.json",
    )
    if os.path.exists(example_path):
        with open(example_path) as f:
            cfg = json.load(f)
        out = generate_urdf(cfg, "/tmp/urdf_generator_test.urdf")
        print(f"[OK] 写入 {out}")
        print(f"      dof={cfg.get('dof')}, joints={list(cfg.get('joints', {}).keys())}")
    else:
        # 直接构造一个最小配置测一下
        cfg = {
            "arm_name": "test",
            "dof": 2,
            "joints": {
                "joint1": {"type":"axial", "link":{"l":0.0,"d":0.08,"alpha":1.5708,"theta":0.0,"mass":0.16,"center_of_mass":[0,0,0.04]}, "actuator_mass":0.055},
                "joint2": {"type":"tangential","link":{"l":0.15,"d":0.0,"alpha":0.0,"theta":1.5708,"mass":0.12,"center_of_mass":[0.075,0,0]}, "actuator_mass":0.045},
            },
        }
        out = generate_urdf(cfg, "/tmp/urdf_generator_test.urdf")
        print(f"[OK] 写入 {out}")
